### ISSUE TITLE
Site build failure

### ISSUE THREAD

**Issue by AdamBD** [vim-conf-live/NeoVimconf-site-2022#54] opened 2022-10-24 16:47 UTC

**Comment by AdamBD** [comment] 2022-10-24 16:47
12:41:24 AM: Waiting for other deploys from your team to complete. Check the queue: https://app.netlify.com/teams/adambd/builds
12:41:50 AM: Build ready to start
12:41:51 AM: build-image version: 8b79b5e0c585f1b3f892b8032389b4b4b188d887 (focal)
12:41:51 AM: build-image tag: v4.14.0
12:41:51 AM: buildbot version: 1e88a9b854b49555d21dc539e2b8bf5fb78a8f57
12:41:51 AM: Fetching cached dependencies
12:41:51 AM: Starting to download cache of 691.3MB
12:41:54 AM: Finished downloading cache in 2.928752676s
12:41:54 AM: Starting to extract cache
12:41:58 AM: Finished extracting cache in 3.78830893s
12:41:58 AM: Finished fetching cache in 6.809420463s
12:41:58 AM: Starting to prepare the repo for build
12:41:58 AM: Preparing Git Reference refs/heads/main
12:41:59 AM: Parsing package.json dependencies
12:42:00 AM: Starting build script
12:42:00 AM: Installing dependencies
12:42:00 AM: Python version set to 2.7
12:42:00 AM: Started restoring cached node version
12:42:01 AM: Finished restoring cached node version
12:42:01 AM: v16.18.0 is already installed.
12:42:01 AM: Now using node v16.18.0 (npm v8.19.2)
12:42:01 AM: Enabling node corepack
12:42:02 AM: Started restoring cached build plugins
12:42:02 AM: Finished restoring cached build plugins
12:42:02 AM: Attempting ruby version 2.7.2, read from environment
12:42:02 AM: Using ruby version 2.7.2
12:42:02 AM: Using PHP version 8.0
12:42:02 AM: Started restoring cached yarn cache
12:42:05 AM: Finished restoring cached yarn cache
12:42:05 AM: No yarn workspaces detected
12:42:05 AM: Started restoring cached node modules
12:42:05 AM: Finished restoring cached node modules
12:42:06 AM: Installing NPM modules using Yarn version 1.22.19
12:42:06 AM: yarn install v1.22.19
12:42:06 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
12:42:06 AM: [1/4] Resolving packages...
12:42:06 AM: [2/4] Fetching packages...
12:42:07 AM: [3/4] Linking dependencies...
12:42:08 AM: [4/4] Building fresh packages...
12:42:08 AM: $ husky install
12:42:08 AM: husky - Git hooks installed
12:42:08 AM: Done in 2.14s.
12:42:08 AM: NPM modules installed using Yarn
12:42:08 AM: Started restoring cached go cache
12:42:08 AM: Finished restoring cached go cache
12:42:08 AM: Installing Go version 1.17 (requested 1.17)
12:42:12 AM: unset GOOS;
12:42:12 AM: unset GOARCH;
12:42:12 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
12:42:12 AM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
12:42:12 AM: go version >&2;
12:42:12 AM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
12:42:12 AM: go version go1.17 linux/amd64
12:42:12 AM: Installing missing commands
12:42:12 AM: Verify run directory
12:42:13 AM: ​
12:42:13 AM: ────────────────────────────────────────────────────────────────
12:42:13 AM:   Netlify Build                                                 
12:42:13 AM: ────────────────────────────────────────────────────────────────
12:42:13 AM: ​
12:42:13 AM: ❯ Version
12:42:13 AM:   @netlify/build 28.1.1
12:42:13 AM: ​
12:42:13 AM: ❯ Flags
12:42:13 AM:   baseRelDir: true
12:42:13 AM:   buildId: 6355b5045299e30008ba45a8
12:42:13 AM:   deployId: 6355b5045299e30008ba45aa
12:42:13 AM: ​
12:42:13 AM: ❯ Current directory
12:42:13 AM:   /opt/build/repo
12:42:13 AM: ​
12:42:13 AM: ❯ Config file
12:42:13 AM:   No config file was defined: using default values.
12:42:13 AM: ​
12:42:13 AM: ❯ Context
12:42:13 AM:   production
12:42:14 AM: ​
12:42:14 AM: ❯ Using Next.js Runtime - v4.27.3
12:42:15 AM: ​
12:42:15 AM: ────────────────────────────────────────────────────────────────
12:42:15 AM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
12:42:15 AM: ────────────────────────────────────────────────────────────────
12:42:15 AM: ​
12:42:15 AM: Next.js cache restored.
12:42:15 AM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
12:42:15 AM: ​
12:42:15 AM: (@netlify/plugin-nextjs onPreBuild completed in 91ms)
12:42:15 AM: ​
12:42:15 AM: ────────────────────────────────────────────────────────────────
12:42:15 AM:   2. Build command from Netlify app                             
12:42:15 AM: ────────────────────────────────────────────────────────────────
12:42:15 AM: ​
12:42:15 AM: $ yarn build
12:42:15 AM: yarn run v1.22.19
12:42:15 AM: $ next build
12:42:15 AM: info  - Linting and checking validity of types...
12:42:18 AM: info  - Creating an optimized production build...
12:42:23 AM: info  - Compiled successfully
12:42:23 AM: info  - Collecting page data...
12:42:23 AM: Error: supabaseUrl is required.
12:42:23 AM:     at new SupabaseClient (/opt/build/repo/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:55:19)
12:42:23 AM:     at createClient (/opt/build/repo/node_modules/@supabase/supabase-js/dist/main/index.js:35:12)
12:42:23 AM:     at Object.3963 (/opt/build/repo/.next/server/pages/registration.js:31:62)
12:42:23 AM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
12:42:23 AM:     at __webpack_exec__ (/opt/build/repo/.next/server/pages/registration.js:379:39)
12:42:23 AM:     at /opt/build/repo/.next/server/pages/registration.js:380:74
12:42:23 AM:     at Function.__webpack_require__.X (/opt/build/repo/.next/server/webpack-runtime.js:108:21)
12:42:23 AM:     at /opt/build/repo/.next/server/pages/registration.js:380:47
12:42:23 AM:     at Object.<anonymous> (/opt/build/repo/.next/server/pages/registration.js:383:3)
12:42:23 AM:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
12:42:23 AM: > Build error occurred
12:42:23 AM: Error: Failed to collect page data for /registration
12:42:23 AM:     at /opt/build/repo/node_modules/next/dist/build/utils.js:771:15
12:42:23 AM:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
12:42:23 AM:   type: 'Error'
12:42:23 AM: }
12:42:23 AM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
12:42:23 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:42:23 AM: ​
12:42:23 AM: ────────────────────────────────────────────────────────────────
12:42:23 AM:   "build.command" failed                                        
12:42:23 AM: ────────────────────────────────────────────────────────────────
12:42:23 AM: ​
12:42:23 AM:   Error message
12:42:23 AM:   Command failed with exit code 1: yarn build (https://ntl.fyi/exit-code-1)
12:42:23 AM: ​
12:42:23 AM:   Error location
12:42:23 AM:   In Build command from Netlify app:
12:42:23 AM:   yarn build
12:42:23 AM: ​
12:42:23 AM:   Resolved config
12:42:23 AM:   build:
12:42:23 AM:     command: yarn build
12:42:23 AM:     commandOrigin: ui
12:42:23 AM:     environment:
12:42:23 AM:       - NEXT_PRIVATE_TARGET
12:42:23 AM:     publish: /opt/build/repo/.next
12:42:23 AM:     publishOrigin: ui
12:42:23 AM:   plugins:
12:42:23 AM:     - inputs: {}
12:42:23 AM:       origin: ui
12:42:23 AM:       package: '@netlify/plugin-nextjs'
12:42:24 AM: Caching artifacts
12:42:24 AM: Started saving node modules
12:42:24 AM: Finished saving node modules
12:42:24 AM: Started saving build plugins
12:42:24 AM: Finished saving build plugins
12:42:24 AM: Started saving yarn cache
12:42:28 AM: Finished saving yarn cache
12:42:28 AM: Started saving pip cache
12:42:28 AM: Finished saving pip cache
12:42:28 AM: Started saving emacs cask dependencies
12:42:28 AM: Finished saving emacs cask dependencies
12:42:28 AM: Started saving maven dependencies
12:42:28 AM: Finished saving maven dependencies
12:42:28 AM: Started saving boot dependencies
12:42:28 AM: Finished saving boot dependencies
12:42:28 AM: Started saving rust rustup cache
12:42:28 AM: Finished saving rust rustup cache
12:42:28 AM: Started saving go dependencies
12:42:28 AM: Finished saving go dependencies
12:42:28 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:42:28 AM: Creating deploy upload records
12:42:28 AM: Failing build: Failed to build site
12:42:28 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:42:28 AM: Finished processing build request in 36.729994287s

**Comment by mvargasmoran** [comment] 2022-10-24 18:55
This was caused by a bit of eagerness in moving to supabase, but now that we have the environment vars up, we shouldn't be seeing this anymore.

**Closed by mvargasmoran** 2022-10-24 18:55 UTC
